import express, { Request, Response } from 'express';
import path from 'path';
import crypto from 'crypto';
import { createServer as createViteServer } from 'vite';
import {
  Tenant,
  User,
  Client,
  Filing,
  DocumentCategory,
  DocumentRequirement,
  DocumentVersion,
  Payment,
  NotificationItem,
  DownloadEvent,
  AuditLog,
  StaffMember,
  FeatureFlags,
  FilingStatus,
  ChatMessage,
} from './src/types';

const PORT = 3000;
const app = express();
app.use(express.json({ limit: '10mb' }));

// Feature Flags
const featureFlags: FeatureFlags = {
  PAYMENTS: true,
  PAN_DOB_VERIFICATION: true,
  PUSH_NOTIFICATIONS: true,
  AI_OCR: false,
  DOCUMENT_CLASSIFICATION: false,
  TAX_RULES: false,
  ITD_ERI: false,
  ITD_PREFILL: false,
  ITD_SUBMISSION: false,
  WHATSAPP: false,
};

// Default Tenant
const tenant: Tenant = {
  id: 'tenant-kothari-01',
  brandName: 'Kothari & Associates Tax Vault',
  logoUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=150&auto=format&fit=crop&q=80',
  primaryColor: '#1e3a8a',
  secondaryColor: '#0d9488',
  supportPhone: '+91 98200 12345',
  supportEmail: 'support@kotharitax.in',
};

// Initial Pre-loaded Data
let users: User[] = [
  {
    id: 'user-ca-admin',
    tenantId: tenant.id,
    mobile: '+91 98200 12345',
    email: 'ca.kothari@kotharitax.in',
    name: 'CA Rajesh Kothari',
    role: 'CA_ADMIN',
  },
  {
    id: 'user-ca-staff-1',
    tenantId: tenant.id,
    mobile: '+91 98200 54321',
    email: 'priya.sharma@kotharitax.in',
    name: 'Priya Sharma (Senior Tax Exec)',
    role: 'CA_STAFF',
  },
  {
    id: 'user-client-1',
    tenantId: tenant.id,
    mobile: '+91 98765 43210',
    email: 'yuvaraj.vasam@example.com',
    name: 'Yuvaraj Vasam',
    role: 'CLIENT',
  },
  {
    id: 'user-client-2',
    tenantId: tenant.id,
    mobile: '+91 98111 22334',
    email: 'rahul.sharma@example.com',
    name: 'Rahul Sharma',
    role: 'CLIENT',
  },
  {
    id: 'user-client-3',
    tenantId: tenant.id,
    mobile: '+91 99887 76655',
    email: 'ananya.patel@example.com',
    name: 'Ananya Patel',
    role: 'CLIENT',
  },
];

let clients: Client[] = [
  {
    id: 'client-1',
    tenantId: tenant.id,
    firstName: 'Yuvaraj',
    lastName: 'Vasam',
    mobile: '+91 98765 43210',
    email: 'yuvaraj.vasam@example.com',
    pan: 'ABCDE1234F',
    dateOfBirth: '2004-08-30',
    address: 'Suite 402, Lotus Towers, Bandra West, Mumbai, MH - 400050',
    clientId: 'TV-2025-001',
    status: 'ACTIVE',
    createdAt: '2025-04-10T09:00:00Z',
  },
  {
    id: 'client-2',
    tenantId: tenant.id,
    firstName: 'Rahul',
    lastName: 'Sharma',
    mobile: '+91 98111 22334',
    email: 'rahul.sharma@example.com',
    pan: 'BNMKL5678G',
    dateOfBirth: '1992-05-14',
    address: 'Flat 12B, Green Acres, Indiranagar, Bengaluru, KA - 560038',
    clientId: 'TV-2025-002',
    status: 'ACTIVE',
    createdAt: '2025-04-12T10:30:00Z',
  },
  {
    id: 'client-3',
    tenantId: tenant.id,
    firstName: 'Ananya',
    lastName: 'Patel',
    mobile: '+91 99887 76655',
    email: 'ananya.patel@example.com',
    pan: 'CPQLM9012H',
    dateOfBirth: '1988-11-22',
    address: '75, CG Road, Navrangpura, Ahmedabad, GJ - 380009',
    clientId: 'TV-2025-003',
    status: 'ACTIVE',
    createdAt: '2025-04-15T14:15:00Z',
  },
];

let categories: DocumentCategory[] = [
  { id: 'cat-1', tenantId: tenant.id, name: 'PAN Card', description: 'Identity and Permanent Account Number proof', isDefault: true },
  { id: 'cat-2', tenantId: tenant.id, name: 'Form 16', description: 'Salary Certificate issued by Employer', isDefault: true },
  { id: 'cat-3', tenantId: tenant.id, name: 'Form 16A', description: 'TDS Certificate for Non-Salary Income', isDefault: true },
  { id: 'cat-4', tenantId: tenant.id, name: 'AIS (Annual Information Statement)', description: 'Income Tax AIS PDF downloaded from ITD portal', isDefault: true },
  { id: 'cat-5', tenantId: tenant.id, name: '26AS Tax Statement', description: 'Form 26AS Tax Credit Statement', isDefault: true },
  { id: 'cat-6', tenantId: tenant.id, name: 'Bank Statement', description: '12-month savings/current bank account statement', isDefault: true },
  { id: 'cat-7', tenantId: tenant.id, name: 'Capital Gains Statement', description: 'Broker report for Equity/Mutual Funds/Crypto/Property gains', isDefault: true },
  { id: 'cat-8', tenantId: tenant.id, name: 'Investment Proof (80C/80D)', description: 'ELSS, PPF, LIC, Health Insurance premium receipts', isDefault: true },
  { id: 'cat-9', tenantId: tenant.id, name: 'Home Loan Certificate', description: 'Interest & principal breakdown for 24b/80C', isDefault: true },
  { id: 'cat-10', tenantId: tenant.id, name: 'ITR Acknowledgement', description: 'Final ITR V acknowledgement generated by CA', isDefault: true },
  { id: 'cat-11', tenantId: tenant.id, name: 'Tax Computation Sheet', description: 'Detailed CA Tax Calculation and summary breakdown', isDefault: true },
];

let filings: Filing[] = [
  {
    id: 'filing-1',
    tenantId: tenant.id,
    clientId: 'client-1',
    clientName: 'Yuvaraj Vasam',
    panMasked: 'XXXXX1234F',
    financialYear: 'FY 2025–26',
    assessmentYear: 'AY 2026–27',
    status: 'PAYMENT_PENDING',
    progress: 85,
    totalDocuments: 6,
    receivedDocuments: 6,
    feeAmount: 2500,
    paymentStatus: 'PENDING',
    panDobVerified: false,
    createdAt: '2026-05-01T08:00:00Z',
    updatedAt: '2026-08-01T12:00:00Z',
  },
  {
    id: 'filing-2',
    tenantId: tenant.id,
    clientId: 'client-2',
    clientName: 'Rahul Sharma',
    panMasked: 'XXXXX5678G',
    financialYear: 'FY 2025–26',
    assessmentYear: 'AY 2026–27',
    status: 'ADDITIONAL_DOCUMENTS_REQUIRED',
    progress: 50,
    totalDocuments: 5,
    receivedDocuments: 3,
    feeAmount: 3000,
    paymentStatus: 'PENDING',
    panDobVerified: false,
    createdAt: '2026-05-02T09:00:00Z',
    updatedAt: '2026-08-05T10:00:00Z',
  },
  {
    id: 'filing-3',
    tenantId: tenant.id,
    clientId: 'client-3',
    clientName: 'Ananya Patel',
    panMasked: 'XXXXX9012H',
    financialYear: 'FY 2025–26',
    assessmentYear: 'AY 2026–27',
    status: 'DOWNLOAD_UNLOCKED',
    progress: 100,
    totalDocuments: 5,
    receivedDocuments: 5,
    feeAmount: 3500,
    paymentStatus: 'SUCCESS',
    panDobVerified: true,
    createdAt: '2026-04-15T08:00:00Z',
    updatedAt: '2026-07-20T11:00:00Z',
  },
];

let requirements: DocumentRequirement[] = [
  // Filing 1 Requirements
  {
    id: 'req-101',
    filingId: 'filing-1',
    documentCategoryId: 'cat-1',
    categoryName: 'PAN Card',
    name: 'PAN Card Copy',
    description: 'Clear image or PDF of PAN Card',
    required: true,
    status: 'APPROVED',
    createdAt: '2026-05-01T08:05:00Z',
    updatedAt: '2026-05-02T10:00:00Z',
    currentDocument: {
      id: 'doc-101',
      status: 'APPROVED',
      latestVersion: {
        id: 'ver-101-1',
        documentId: 'doc-101',
        versionNumber: 1,
        fileName: 'Yuvaraj_PAN_Card.pdf',
        fileType: 'application/pdf',
        fileSize: 450000,
        contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        uploadedAt: '2026-05-01T10:00:00Z',
        uploadedBy: 'Yuvaraj Vasam',
      },
      versions: [
        {
          id: 'ver-101-1',
          documentId: 'doc-101',
          versionNumber: 1,
          fileName: 'Yuvaraj_PAN_Card.pdf',
          fileType: 'application/pdf',
          fileSize: 450000,
          contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
          uploadedAt: '2026-05-01T10:00:00Z',
          uploadedBy: 'Yuvaraj Vasam',
        },
      ],
    },
  },
  {
    id: 'req-102',
    filingId: 'filing-1',
    documentCategoryId: 'cat-2',
    categoryName: 'Form 16',
    name: 'Form 16 Part A & B',
    description: 'Employer salary certificate for FY 2025-26',
    required: true,
    status: 'APPROVED',
    createdAt: '2026-05-01T08:05:00Z',
    updatedAt: '2026-05-03T11:00:00Z',
    currentDocument: {
      id: 'doc-102',
      status: 'APPROVED',
      latestVersion: {
        id: 'ver-102-1',
        documentId: 'doc-102',
        versionNumber: 1,
        fileName: 'Form16_FY2025_26_TCS.pdf',
        fileType: 'application/pdf',
        fileSize: 1200000,
        contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        uploadedAt: '2026-05-02T14:20:00Z',
        uploadedBy: 'Yuvaraj Vasam',
      },
      versions: [],
    },
  },
  {
    id: 'req-103',
    filingId: 'filing-1',
    documentCategoryId: 'cat-4',
    categoryName: 'AIS (Annual Information Statement)',
    name: 'AIS Summary PDF',
    description: 'Downloaded from ITD compliance portal',
    required: true,
    status: 'APPROVED',
    createdAt: '2026-05-01T08:05:00Z',
    updatedAt: '2026-05-04T12:00:00Z',
    currentDocument: {
      id: 'doc-103',
      status: 'APPROVED',
      latestVersion: {
        id: 'ver-103-1',
        documentId: 'doc-103',
        versionNumber: 1,
        fileName: 'AIS_Yuvaraj_2025_26.pdf',
        fileType: 'application/pdf',
        fileSize: 890000,
        contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        uploadedAt: '2026-05-04T09:15:00Z',
        uploadedBy: 'Yuvaraj Vasam',
      },
      versions: [],
    },
  },
  {
    id: 'req-104',
    filingId: 'filing-1',
    documentCategoryId: 'cat-6',
    categoryName: 'Bank Statement',
    name: 'HDFC Savings Bank Statement',
    description: 'April 2025 to March 2026',
    required: true,
    status: 'APPROVED',
    createdAt: '2026-05-01T08:05:00Z',
    updatedAt: '2026-05-05T16:00:00Z',
    currentDocument: {
      id: 'doc-104',
      status: 'APPROVED',
      latestVersion: {
        id: 'ver-104-2',
        documentId: 'doc-104',
        versionNumber: 2,
        fileName: 'HDFC_Statement_Full_FY2526.pdf',
        fileType: 'application/pdf',
        fileSize: 2100000,
        contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        uploadedAt: '2026-05-05T15:30:00Z',
        uploadedBy: 'Yuvaraj Vasam',
      },
      versions: [],
    },
  },
  {
    id: 'req-105',
    filingId: 'filing-1',
    documentCategoryId: 'cat-10',
    categoryName: 'ITR Acknowledgement',
    name: 'ITR-V Filing Acknowledgement (CA Upload)',
    description: 'Final verified income tax acknowledgement uploaded by CA',
    required: true,
    status: 'APPROVED',
    createdAt: '2026-08-01T11:00:00Z',
    updatedAt: '2026-08-01T12:00:00Z',
    currentDocument: {
      id: 'doc-105',
      status: 'APPROVED',
      latestVersion: {
        id: 'ver-105-1',
        documentId: 'doc-105',
        versionNumber: 1,
        fileName: 'ITR_V_Acknowledgement_Yuvaraj_FY2526.pdf',
        fileType: 'application/pdf',
        fileSize: 640000,
        contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        uploadedAt: '2026-08-01T12:00:00Z',
        uploadedBy: 'CA Rajesh Kothari',
      },
      versions: [],
    },
  },
  {
    id: 'req-106',
    filingId: 'filing-1',
    documentCategoryId: 'cat-11',
    categoryName: 'Tax Computation Sheet',
    name: 'Detailed Tax Computation Sheet',
    description: 'Certified computation sheet prepared by Kothari & Associates',
    required: true,
    status: 'APPROVED',
    createdAt: '2026-08-01T11:00:00Z',
    updatedAt: '2026-08-01T12:00:00Z',
    currentDocument: {
      id: 'doc-106',
      status: 'APPROVED',
      latestVersion: {
        id: 'ver-106-1',
        documentId: 'doc-106',
        versionNumber: 1,
        fileName: 'Tax_Computation_Yuvaraj_FY2526.pdf',
        fileType: 'application/pdf',
        fileSize: 520000,
        contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        uploadedAt: '2026-08-01T12:00:00Z',
        uploadedBy: 'CA Rajesh Kothari',
      },
      versions: [],
    },
  },
  {
    id: 'req-107',
    filingId: 'filing-1',
    documentCategoryId: 'cat-12',
    categoryName: 'CA Compliance Certificate',
    name: 'CA Return Verification & Filing Receipt',
    description: 'Formal digitally signed verification receipt issued by Chartered Accountant',
    required: true,
    status: 'APPROVED',
    createdAt: '2026-08-01T11:30:00Z',
    updatedAt: '2026-08-01T12:30:00Z',
    currentDocument: {
      id: 'doc-107',
      status: 'APPROVED',
      latestVersion: {
        id: 'ver-107-1',
        documentId: 'doc-107',
        versionNumber: 1,
        fileName: 'CA_Certified_Filing_Receipt_Yuvaraj.pdf',
        fileType: 'application/pdf',
        fileSize: 410000,
        contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        uploadedAt: '2026-08-01T12:30:00Z',
        uploadedBy: 'CA Rajesh Kothari',
      },
      versions: [],
    },
  },

  // Filing 2 Requirements (Rahul Sharma - Missing Docs)
  {
    id: 'req-201',
    filingId: 'filing-2',
    documentCategoryId: 'cat-1',
    categoryName: 'PAN Card',
    name: 'PAN Card Copy',
    description: 'PAN card upload',
    required: true,
    status: 'APPROVED',
    createdAt: '2026-05-02T09:10:00Z',
    updatedAt: '2026-05-03T10:00:00Z',
    currentDocument: {
      id: 'doc-201',
      status: 'APPROVED',
      latestVersion: {
        id: 'ver-201-1',
        documentId: 'doc-201',
        versionNumber: 1,
        fileName: 'Rahul_PAN.pdf',
        fileType: 'application/pdf',
        fileSize: 310000,
        contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        uploadedAt: '2026-05-02T12:00:00Z',
        uploadedBy: 'Rahul Sharma',
      },
      versions: [],
    },
  },
  {
    id: 'req-202',
    filingId: 'filing-2',
    documentCategoryId: 'cat-7',
    categoryName: 'Capital Gains Statement',
    name: 'Zerodha Annual Capital Gains Report',
    description: 'FY 2025-26 STCG/LTCG breakdown required for ITR-2',
    required: true,
    status: 'REJECTED',
    rejectionReason: 'Uploaded statement is incomplete. Pages 3-5 showing quarterly trading details are missing.',
    createdAt: '2026-05-02T09:10:00Z',
    updatedAt: '2026-08-05T10:00:00Z',
    currentDocument: {
      id: 'doc-202',
      status: 'REJECTED',
      latestVersion: {
        id: 'ver-202-1',
        documentId: 'doc-202',
        versionNumber: 1,
        fileName: 'Zerodha_Summary_Partial.pdf',
        fileType: 'application/pdf',
        fileSize: 300000,
        contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        uploadedAt: '2026-08-04T11:00:00Z',
        uploadedBy: 'Rahul Sharma',
      },
      versions: [],
    },
  },
  {
    id: 'req-203',
    filingId: 'filing-2',
    documentCategoryId: 'cat-6',
    categoryName: 'Bank Statement',
    name: 'ICICI Bank Statement',
    description: 'Savings account statement for FY 2025-26',
    required: true,
    status: 'PENDING',
    createdAt: '2026-08-05T10:00:00Z',
    updatedAt: '2026-08-05T10:00:00Z',
  },
];

let payments: Payment[] = [
  {
    id: 'pay-301',
    tenantId: tenant.id,
    clientId: 'client-3',
    filingId: 'filing-3',
    razorpayOrderId: 'order_RZP901238',
    razorpayPaymentId: 'pay_RZP88776655',
    amount: 3500,
    currency: 'INR',
    status: 'SUCCESS',
    paymentMethod: 'UPI / Google Pay',
    paidAt: '2026-07-20T11:00:00Z',
    createdAt: '2026-07-20T10:55:00Z',
  },
];

let notifications: NotificationItem[] = [
  {
    id: 'notif-1',
    tenantId: tenant.id,
    clientId: 'client-1',
    filingId: 'filing-1',
    type: 'DOCUMENTS_READY',
    title: 'Filing Complete & Documents Ready',
    message: 'Your FY 2025–26 tax filing is completed. Complete payment to unlock your secure tax vault.',
    read: false,
    createdAt: '2026-08-01T12:05:00Z',
  },
  {
    id: 'notif-2',
    tenantId: tenant.id,
    clientId: 'client-2',
    filingId: 'filing-2',
    type: 'DOCUMENT_REJECTED',
    title: 'Replacement Requested for Capital Gains Statement',
    message: 'Uploaded statement is incomplete. Pages 3-5 showing quarterly trading details are missing.',
    read: false,
    createdAt: '2026-08-05T10:02:00Z',
  },
];

let auditLogs: AuditLog[] = [
  {
    id: 'audit-1',
    tenantId: tenant.id,
    actorId: 'user-ca-admin',
    actorName: 'CA Rajesh Kothari',
    actorType: 'CA_ADMIN',
    action: 'FILING_COMPLETED',
    entityType: 'Filing',
    entityId: 'filing-1',
    metadata: { clientName: 'Yuvaraj Vasam', financialYear: 'FY 2025–26' },
    ipAddress: '103.21.124.89',
    createdAt: '2026-08-01T12:00:00Z',
  },
  {
    id: 'audit-2',
    tenantId: tenant.id,
    actorId: 'user-ca-staff-1',
    actorName: 'Priya Sharma',
    actorType: 'CA_STAFF',
    action: 'DOCUMENT_REJECTED',
    entityType: 'DocumentRequirement',
    entityId: 'req-202',
    metadata: { clientName: 'Rahul Sharma', category: 'Capital Gains Statement' },
    ipAddress: '103.21.124.90',
    createdAt: '2026-08-05T10:00:00Z',
  },
];

let downloadEvents: DownloadEvent[] = [
  {
    id: 'dl-101',
    tenantId: tenant.id,
    clientId: 'client-3',
    filingId: 'filing-3',
    documentId: 'doc-301',
    documentName: 'ITR-V Acknowledgement FY2526',
    userId: 'user-client-3',
    userName: 'Ananya Patel',
    timestamp: '2026-07-20T11:15:00Z',
    ipAddress: '49.36.120.14',
    userAgent: 'TaxVault Mobile Android 2.4.0',
    success: true,
  },
];

let staffMembers: StaffMember[] = [
  {
    id: 'staff-1',
    tenantId: tenant.id,
    userId: 'user-ca-staff-1',
    name: 'Priya Sharma',
    email: 'priya.sharma@kotharitax.in',
    mobile: '+91 98200 54321',
    role: 'CA_STAFF',
    permissions: ['clients:read', 'filings:read', 'filings:update', 'documents:read', 'documents:approve', 'documents:reject'],
    status: 'ACTIVE',
    createdAt: '2025-04-01T10:00:00Z',
  },
];

let chatMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    tenantId: tenant.id,
    clientId: 'client-1',
    senderId: 'user-ca-admin',
    senderName: 'CA Rajesh Kothari',
    senderRole: 'CA_ADMIN',
    message: 'Hello Yuvaraj, we have reviewed your Form 16 and bank interest details for FY 2025–26. Your tax computation is ready.',
    read: true,
    createdAt: '2026-08-01T10:30:00Z',
  },
  {
    id: 'msg-2',
    tenantId: tenant.id,
    clientId: 'client-1',
    senderId: 'user-client-1',
    senderName: 'Yuvaraj Vasam',
    senderRole: 'CLIENT',
    message: 'Thank you Sir! Does this include the Section 80C deductions for my PPF contribution of ₹1.5 Lakhs?',
    read: true,
    createdAt: '2026-08-01T10:45:00Z',
  },
  {
    id: 'msg-3',
    tenantId: tenant.id,
    clientId: 'client-1',
    senderId: 'user-ca-admin',
    senderName: 'CA Rajesh Kothari',
    senderRole: 'CA_ADMIN',
    message: 'Yes, full ₹1,50,000 under 80C and ₹50,000 standard deduction have been claimed. You can review the draft and unlock your final ITR-V acknowledgement.',
    read: true,
    createdAt: '2026-08-01T11:00:00Z',
  },
  {
    id: 'msg-4',
    tenantId: tenant.id,
    clientId: 'client-2',
    senderId: 'user-ca-staff-1',
    senderName: 'Priya Sharma',
    senderRole: 'CA_STAFF',
    message: 'Hi Rahul, the capital gains statement you uploaded is missing pages 3–5 with quarterly transaction breakdowns. Could you please re-upload the full PDF?',
    read: false,
    createdAt: '2026-08-05T10:05:00Z',
  },
];

// PAN Identity verification rate limiting memory map: clientId -> { attempts, lockedUntil }
const panVerificationAttemptsMap = new Map<string, { attempts: number; lockedUntil?: number }>();

// Helper logging audit
function recordAudit(actorId: string, actorName: string, actorType: 'CA_ADMIN' | 'CA_STAFF' | 'CLIENT' | 'SYSTEM', action: string, entityType: string, entityId: string, metadata?: Record<string, unknown>, reqIp?: string) {
  const log: AuditLog = {
    id: `audit-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
    tenantId: tenant.id,
    actorId,
    actorName,
    actorType,
    action,
    entityType,
    entityId,
    metadata,
    ipAddress: reqIp || '127.0.0.1',
    createdAt: new Date().toISOString(),
  };
  auditLogs.unshift(log);
}

// REST API ROUTES

// TENANT
app.get('/api/tenant', (req: Request, res: Response) => {
  res.json(tenant);
});

app.get('/api/users', (req: Request, res: Response) => {
  res.json(users);
});

app.patch('/api/tenant', (req: Request, res: Response) => {
  Object.assign(tenant, req.body);
  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'TENANT_UPDATED', 'Tenant', tenant.id, req.body, req.ip);
  res.json(tenant);
});

// CLIENTS DIRECT API
app.get('/api/clients', (req: Request, res: Response) => {
  const { search } = req.query;
  let result = [...clients];
  if (search) {
    const q = (search as string).toLowerCase();
    result = result.filter((c) => c.firstName.toLowerCase().includes(q) || c.lastName.toLowerCase().includes(q) || c.pan.toLowerCase().includes(q) || c.mobile.includes(q) || c.clientId.toLowerCase().includes(q));
  }
  res.json(result);
});

app.post('/api/clients', (req: Request, res: Response) => {
  const { firstName, lastName, mobile, email, pan, dateOfBirth, address } = req.body;
  const newClient: Client = {
    id: `client-${Date.now()}`,
    tenantId: tenant.id,
    firstName: firstName || 'New',
    lastName: lastName || 'Client',
    mobile: mobile || '+91 98000 00000',
    email: email || '',
    pan: (pan || 'ABCDE1234F').toUpperCase(),
    dateOfBirth: dateOfBirth || '1995-01-01',
    address: address || '',
    clientId: `TV-2025-${String(clients.length + 1).padStart(3, '0')}`,
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  };
  clients.unshift(newClient);
  users.push({
    id: `user-${newClient.id}`,
    tenantId: tenant.id,
    mobile: newClient.mobile,
    email: newClient.email,
    name: `${newClient.firstName} ${newClient.lastName}`.trim(),
    role: 'CLIENT',
  });
  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'CLIENT_CREATED', 'Client', newClient.id, { clientName: `${firstName} ${lastName}`, pan }, req.ip);
  res.json(newClient);
});

// FILINGS DIRECT API
app.get('/api/filings', (req: Request, res: Response) => {
  const clientId = req.query.clientId as string;
  let list = [...filings];
  if (clientId) {
    list = list.filter((f) => f.clientId === clientId);
  }
  res.json(list);
});

app.post('/api/filings', (req: Request, res: Response) => {
  const { clientId, financialYear, assessmentYear, feeAmount } = req.body;
  const client = clients.find((c) => c.id === clientId) || clients[0];
  const newFiling: Filing = {
    id: `filing-${Date.now()}`,
    tenantId: tenant.id,
    clientId: client.id,
    clientName: `${client.firstName} ${client.lastName}`.trim(),
    panMasked: `${client.pan.slice(0, 2)}XXX${client.pan.slice(-4)}`,
    financialYear: financialYear || 'FY 2025–26',
    assessmentYear: assessmentYear || 'AY 2026–27',
    status: 'DOCUMENTS_REQUESTED',
    progress: 0,
    totalDocuments: 4,
    receivedDocuments: 0,
    feeAmount: feeAmount || 2500,
    paymentStatus: 'PENDING',
    panDobVerified: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  ['cat-1', 'cat-2', 'cat-4', 'cat-6'].forEach((catId, idx) => {
    const cat = categories.find((c) => c.id === catId);
    if (cat) {
      requirements.push({
        id: `req-${Date.now()}-${idx}`,
        filingId: newFiling.id,
        documentCategoryId: cat.id,
        categoryName: cat.name,
        name: cat.name + ' Copy',
        description: cat.description,
        required: true,
        status: 'PENDING',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      });
    }
  });

  filings.unshift(newFiling);
  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'FILING_CREATED', 'Filing', newFiling.id, { clientName: newFiling.clientName, FY: newFiling.financialYear }, req.ip);
  res.json(newFiling);
});

app.patch('/api/filings/:id/status', (req: Request, res: Response) => {
  const { status } = req.body;
  const filing = filings.find((f) => f.id === req.params.id);
  if (filing) {
    filing.status = status;
    filing.updatedAt = new Date().toISOString();
    recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'FILING_STATUS_CHANGED', 'Filing', filing.id, { newStatus: status }, req.ip);
  }
  res.json({ success: true, filing });
});

// DOCUMENTS & REQUIREMENTS DIRECT API
app.get('/api/documents/requirements', (req: Request, res: Response) => {
  res.json(requirements);
});

app.post('/api/documents/:reqId/approve', (req: Request, res: Response) => {
  const reqItem = requirements.find((r) => r.id === req.params.reqId);
  if (reqItem) {
    reqItem.status = 'APPROVED';
    if (reqItem.currentDocument) {
      reqItem.currentDocument.status = 'APPROVED';
    }
    reqItem.rejectionReason = undefined;
    reqItem.updatedAt = new Date().toISOString();

    const filing = filings.find((f) => f.id === reqItem.filingId);
    if (filing) {
      const filingReqs = requirements.filter((r) => r.filingId === filing.id);
      const approvedCount = filingReqs.filter((r) => r.status === 'APPROVED').length;
      filing.receivedDocuments = approvedCount;
      filing.progress = Math.round((approvedCount / Math.max(1, filing.totalDocuments)) * 80);
    }
    recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'DOCUMENT_APPROVED', 'DocumentRequirement', reqItem.id, { name: reqItem.name }, req.ip);
  }
  res.json({ success: true, requirement: reqItem });
});

app.post('/api/documents/:reqId/reject', (req: Request, res: Response) => {
  const { reason } = req.body;
  const reqItem = requirements.find((r) => r.id === req.params.reqId);
  if (reqItem) {
    reqItem.status = 'REJECTED';
    if (reqItem.currentDocument) {
      reqItem.currentDocument.status = 'REJECTED';
    }
    reqItem.rejectionReason = reason || 'Document rejected by CA. Please re-upload.';
    reqItem.updatedAt = new Date().toISOString();

    const filing = filings.find((f) => f.id === reqItem.filingId);
    if (filing) {
      filing.status = 'ADDITIONAL_DOCUMENTS_REQUIRED';
    }
    recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'DOCUMENT_REJECTED', 'DocumentRequirement', reqItem.id, { reason }, req.ip);
  }
  res.json({ success: true, requirement: reqItem });
});

app.post('/api/documents/request-additional', (req: Request, res: Response) => {
  const { filingId, categoryId, name, description } = req.body;
  const filing = filings.find((f) => f.id === filingId);
  const cat = categories.find((c) => c.id === categoryId) || categories[0];
  const newReq: DocumentRequirement = {
    id: `req-${Date.now()}`,
    filingId: filingId || '',
    documentCategoryId: cat?.id || 'cat-1',
    categoryName: cat?.name || 'Additional Document',
    name: name || cat?.name || 'Additional Requirement',
    description: description || '',
    required: true,
    status: 'PENDING',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  requirements.push(newReq);
  if (filing) {
    filing.totalDocuments += 1;
    filing.status = 'ADDITIONAL_DOCUMENTS_REQUIRED';
  }
  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'DOCUMENT_REQUESTED', 'DocumentRequirement', newReq.id, { name: newReq.name }, req.ip);
  res.json({ success: true, requirement: newReq });
});

app.post('/api/documents/upload-final', (req: Request, res: Response) => {
  const { filingId, title, fileName } = req.body;
  const filing = filings.find((f) => f.id === filingId);
  const newReq: DocumentRequirement = {
    id: `req-final-${Date.now()}`,
    filingId: filingId || '',
    documentCategoryId: 'cat-10',
    categoryName: 'ITR Acknowledgement & Tax Computation',
    name: title || 'ITR V Acknowledgement & Computation',
    description: 'Final verified tax documents generated by CA',
    required: true,
    status: 'APPROVED',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    currentDocument: {
      id: `doc-final-${Date.now()}`,
      status: 'APPROVED',
      latestVersion: {
        id: `ver-final-${Date.now()}`,
        documentId: `doc-final-${Date.now()}`,
        versionNumber: 1,
        fileName: fileName || 'ITR_V_Acknowledgement_Verified.pdf',
        fileType: 'application/pdf',
        fileSize: 750000,
        contentUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        uploadedAt: new Date().toISOString(),
        uploadedBy: 'CA Rajesh Kothari',
      },
      versions: [],
    },
  };
  requirements.push(newReq);
  if (filing) {
    filing.status = 'PAYMENT_PENDING';
    filing.progress = 95;
  }
  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'FINAL_DOCUMENTS_UPLOADED', 'Filing', filingId, { fileName }, req.ip);
  res.json({ success: true, requirement: newReq });
});

app.post('/api/documents/:reqId/upload', (req: Request, res: Response) => {
  const { uploadedBy, fileName, fileType, fileSize, contentUrl } = req.body;
  const reqItem = requirements.find((r) => r.id === req.params.reqId);
  if (reqItem) {
    const newVer = {
      id: `ver-${Date.now()}`,
      documentId: reqItem.currentDocument?.id || `doc-${Date.now()}`,
      versionNumber: (reqItem.currentDocument?.versions?.length || 0) + 1,
      fileName: fileName || 'Uploaded_Document.pdf',
      fileType: fileType || 'application/pdf',
      fileSize: fileSize || 500000,
      contentUrl: contentUrl || 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      uploadedAt: new Date().toISOString(),
      uploadedBy: uploadedBy || 'Client',
    };

    if (!reqItem.currentDocument) {
      reqItem.currentDocument = {
        id: newVer.documentId,
        status: 'UNDER_REVIEW',
        latestVersion: newVer,
        versions: [newVer],
      };
    } else {
      reqItem.currentDocument.versions.unshift(newVer);
      reqItem.currentDocument.latestVersion = newVer;
      reqItem.currentDocument.status = 'UNDER_REVIEW';
    }
    reqItem.status = 'UNDER_REVIEW';
    reqItem.rejectionReason = undefined;
    reqItem.updatedAt = new Date().toISOString();

    const filing = filings.find((f) => f.id === reqItem.filingId);
    if (filing) {
      const filingReqs = requirements.filter((r) => r.filingId === filing.id);
      const received = filingReqs.filter((r) => r.status === 'APPROVED' || r.status === 'UNDER_REVIEW').length;
      filing.receivedDocuments = received;
      filing.progress = Math.round((received / Math.max(1, filing.totalDocuments)) * 80);
      if (filing.status === 'DOCUMENTS_REQUESTED' || filing.status === 'ADDITIONAL_DOCUMENTS_REQUIRED') {
        filing.status = 'DOCUMENTS_PARTIALLY_SUBMITTED';
      }
      if (received >= filing.totalDocuments) {
        filing.status = 'DOCUMENTS_SUBMITTED';
      }
    }
    recordAudit('user-client-1', uploadedBy || 'Client', 'CLIENT', 'DOCUMENT_UPLOADED', 'DocumentRequirement', reqItem.id, { fileName }, req.ip);
  }
  res.json({ success: true, requirement: reqItem });
});

app.post('/api/documents/:reqId/download', (req: Request, res: Response) => {
  const reqItem = requirements.find((r) => r.id === req.params.reqId);
  if (!reqItem || !reqItem.currentDocument) {
    return res.status(404).json({ error: 'Document not found' });
  }

  const filing = filings.find((f) => f.id === reqItem.filingId);
  if (filing) {
    if (filing.paymentStatus !== 'SUCCESS') {
      return res.status(403).json({ error: 'Fee payment is pending. Please complete fee payment to unlock tax vault download.' });
    }
    if (!filing.panDobVerified) {
      return res.status(403).json({ error: 'Identity verification required. Please verify PAN and Date of Birth first.' });
    }
  }

  const version = reqItem.currentDocument.latestVersion;
  const dlEvent: DownloadEvent = {
    id: `dl-${Date.now()}`,
    tenantId: tenant.id,
    clientId: filing?.clientId || 'client-1',
    filingId: filing?.id || '',
    documentId: reqItem.currentDocument.id,
    documentName: reqItem.name,
    userId: 'user-client-1',
    userName: req.body.userName || 'Client',
    timestamp: new Date().toISOString(),
    ipAddress: req.ip || '127.0.0.1',
    userAgent: (req.headers['user-agent'] as string) || 'TaxVault Client Web',
    success: true,
  };
  downloadEvents.unshift(dlEvent);
  recordAudit('user-client-1', dlEvent.userName, 'CLIENT', 'DOCUMENT_DOWNLOADED', 'DocumentRequirement', reqItem.id, { name: reqItem.name }, req.ip);

  res.json({
    success: true,
    downloadUrl: version?.contentUrl || 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileName: version?.fileName || 'Tax_Document.pdf',
  });
});

// PAYMENTS DIRECT API
app.get('/api/payments', (req: Request, res: Response) => {
  res.json(payments);
});

app.post('/api/payments/:filingId/pay', (req: Request, res: Response) => {
  const filing = filings.find((f) => f.id === req.params.filingId);
  if (filing) {
    filing.paymentStatus = 'SUCCESS';
    filing.status = 'PAYMENT_COMPLETED';
    filing.progress = 98;
    const newPay: Payment = {
      id: `pay-${Date.now()}`,
      tenantId: tenant.id,
      clientId: filing.clientId,
      filingId: filing.id,
      razorpayOrderId: `order_${Date.now()}`,
      razorpayPaymentId: `pay_${Date.now()}`,
      amount: filing.feeAmount,
      currency: 'INR',
      status: 'SUCCESS',
      paymentMethod: 'UPI / Razorpay',
      paidAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    };
    payments.unshift(newPay);
    recordAudit('user-client-1', filing.clientName, 'CLIENT', 'PAYMENT_COMPLETED', 'Payment', newPay.id, { amount: newPay.amount }, req.ip);
  }
  res.json({ success: true });
});

// IDENTITY VERIFICATION
app.post('/api/auth/verify-pan-dob', (req: Request, res: Response) => {
  const { filingId, pan, dateOfBirth } = req.body;
  const filing = filings.find((f) => f.id === filingId);
  if (!filing) {
    return res.status(404).json({ success: false, error: 'Filing not found' });
  }
  const client = clients.find((c) => c.id === filing.clientId);
  if (!client) {
    return res.status(404).json({ success: false, error: 'Client not found' });
  }

  const cleanPan = (pan || '').trim().toUpperCase();
  const cleanDob = (dateOfBirth || '').trim();

  if (cleanPan === client.pan && cleanDob === client.dateOfBirth) {
    filing.panDobVerified = true;
    if (filing.paymentStatus === 'SUCCESS') {
      filing.status = 'DOWNLOAD_UNLOCKED';
      filing.progress = 100;
    }
    recordAudit('user-client-1', `${client.firstName} ${client.lastName}`, 'CLIENT', 'PAN_VERIFICATION_SUCCESS', 'Client', client.id, {}, req.ip);
    return res.json({ success: true });
  }

  recordAudit('user-client-1', `${client.firstName} ${client.lastName}`, 'CLIENT', 'PAN_VERIFICATION_FAILED', 'Client', client.id, {}, req.ip);
  return res.status(401).json({ success: false, error: 'PAN or Date of Birth mismatch.' });
});

// AUDIT & DOWNLOAD HISTORY
app.get('/api/audit', (req: Request, res: Response) => {
  res.json(auditLogs);
});

app.get('/api/download-events', (req: Request, res: Response) => {
  res.json(downloadEvents);
});

// STAFF & PERMISSIONS DIRECT API
app.get('/api/staff', (req: Request, res: Response) => {
  res.json(staffMembers);
});

app.post('/api/staff/invite', (req: Request, res: Response) => {
  const { name, email, mobile, permissions } = req.body;
  const staff: StaffMember = {
    id: `staff-${Date.now()}`,
    tenantId: tenant.id,
    userId: `user-staff-${Date.now()}`,
    name: name || 'Staff Member',
    email: email || 'staff@example.com',
    mobile: mobile || '+91 98000 00000',
    role: 'CA_STAFF',
    permissions: permissions || ['clients:read', 'filings:read', 'documents:read', 'documents:approve'],
    status: 'INVITED',
    createdAt: new Date().toISOString(),
  };
  staffMembers.unshift(staff);
  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'STAFF_INVITED', 'StaffMember', staff.id, { email }, req.ip);
  res.json(staff);
});

// FEATURE FLAGS & CATEGORIES DIRECT API
app.get('/api/feature-flags', (req: Request, res: Response) => {
  res.json(featureFlags);
});

app.get('/api/categories', (req: Request, res: Response) => {
  res.json(categories);
});

app.post('/api/categories', (req: Request, res: Response) => {
  const { name, description } = req.body;
  const cat: DocumentCategory = {
    id: `cat-${Date.now()}`,
    tenantId: tenant.id,
    name: name || 'New Category',
    description: description || '',
    isDefault: false,
  };
  categories.push(cat);
  res.json(cat);
});

// CHAT DIRECT API
app.get('/api/chat', (req: Request, res: Response) => {
  const { clientId } = req.query;
  let list = [...chatMessages];
  if (clientId) {
    list = list.filter((m) => m.clientId === clientId);
  }
  res.json(list);
});

app.post('/api/chat', (req: Request, res: Response) => {
  const { clientId, senderId, senderName, senderRole, message, attachments } = req.body;
  const client = clients.find((c) => c.id === clientId) || clients[0];
  
  const newMsg: ChatMessage = {
    id: `msg-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
    tenantId: tenant.id,
    clientId: client ? client.id : (clientId || 'client-1'),
    senderId: senderId || (senderRole === 'CLIENT' ? `user-${clientId}` : 'user-ca-admin'),
    senderName: senderName || (senderRole === 'CLIENT' ? `${client?.firstName} ${client?.lastName}` : 'CA Rajesh Kothari'),
    senderRole: senderRole || 'CA_ADMIN',
    message: message || '',
    attachments: attachments || [],
    read: false,
    createdAt: new Date().toISOString(),
  };

  chatMessages.push(newMsg);

  // If CA / Staff sends a message, generate an in-app client notification
  if (newMsg.senderRole === 'CA_ADMIN' || newMsg.senderRole === 'CA_STAFF') {
    const notif: NotificationItem = {
      id: `notif-${Date.now()}`,
      tenantId: tenant.id,
      clientId: newMsg.clientId,
      type: 'DOCUMENT_REQUESTED',
      title: `Message from ${newMsg.senderName}`,
      message: newMsg.message.slice(0, 120) + (newMsg.message.length > 120 ? '...' : ''),
      read: false,
      createdAt: new Date().toISOString(),
    };
    notifications.unshift(notif);
  }

  recordAudit(
    newMsg.senderId,
    newMsg.senderName,
    newMsg.senderRole,
    'CHAT_MESSAGE_SENT',
    'ChatMessage',
    newMsg.id,
    { clientId: newMsg.clientId, length: newMsg.message.length },
    req.ip
  );

  res.json(newMsg);
});

app.patch('/api/chat/read', (req: Request, res: Response) => {
  const { clientId, readerRole } = req.body;
  let updatedCount = 0;
  chatMessages.forEach((msg) => {
    if ((!clientId || msg.clientId === clientId) && msg.senderRole !== readerRole) {
      msg.read = true;
      updatedCount++;
    }
  });
  res.json({ success: true, updatedCount });
});

// AUTH - DIRECT LOGIN & SIGNUP FOR CLIENT & ADMIN
const userPasswords = new Map<string, string>([
  ['ca.kothari@kotharitax.in', 'admin123'],
  ['priya.sharma@kotharitax.in', 'staff123'],
  ['yuvaraj.vasam@example.com', 'client123'],
  ['rahul.sharma@example.com', 'client123'],
  ['ananya.patel@example.com', 'client123'],
]);

app.post('/api/auth/login', (req: Request, res: Response) => {
  try {
    const { emailOrMobile, password, role } = req.body;
    const input = (emailOrMobile || '').trim().toLowerCase();
    const panInput = (emailOrMobile || '').trim().toUpperCase();

    if (!input) {
      return res.status(400).json({ success: false, error: 'Email, mobile number, or PAN is required.' });
    }

    // Look for user by email, mobile, or linked client PAN
    let matchedUser = users.find(
      (u) =>
        (u.email && u.email.toLowerCase() === input) ||
        (u.mobile && u.mobile.replace(/\D/g, '').endsWith(input.replace(/\D/g, ''))) ||
        (role === 'CLIENT' && clients.some((c) => c.pan === panInput && c.email.toLowerCase() === u.email.toLowerCase()))
    );

    // If searching by PAN for client
    if (!matchedUser && role === 'CLIENT') {
      const matchedClient = clients.find((c) => c.pan === panInput || c.mobile.includes(input) || c.email.toLowerCase() === input);
      if (matchedClient) {
        matchedUser = users.find((u) => u.email.toLowerCase() === matchedClient.email.toLowerCase() || u.mobile === matchedClient.mobile);
        if (!matchedUser) {
          matchedUser = {
            id: `user-${matchedClient.id}`,
            tenantId: tenant.id,
            mobile: matchedClient.mobile,
            email: matchedClient.email,
            name: `${matchedClient.firstName} ${matchedClient.lastName}`.trim(),
            role: 'CLIENT',
          };
          users.push(matchedUser);
        }
      }
    }

    // Fallback demo matching if specific role is requested
    if (!matchedUser) {
      if (role === 'CA_ADMIN' || role === 'ADMIN') {
        matchedUser = users.find((u) => u.role === 'CA_ADMIN') || users[0];
      } else if (role === 'CLIENT') {
        matchedUser = users.find((u) => u.role === 'CLIENT') || users[2];
      }
    }

    if (!matchedUser) {
      return res.status(401).json({ success: false, error: 'Account not found. Please check your credentials or create a new account.' });
    }

    // Validate role isolation
    if ((role === 'CA_ADMIN' || role === 'ADMIN') && matchedUser.role !== 'CA_ADMIN') {
      return res.status(403).json({ success: false, error: 'Access denied. This account does not have CA Admin privileges. Please use the Client Portal.' });
    }
    if (role === 'CLIENT' && matchedUser.role !== 'CLIENT') {
      return res.status(403).json({ success: false, error: 'This is a CA Admin account. Please sign in via the Admin Portal.' });
    }

    // Optional password check (allow demo passwords or registered passwords)
    const storedPassword = userPasswords.get(matchedUser.email.toLowerCase());
    if (storedPassword && password && password !== storedPassword && password !== 'admin123' && password !== 'client123' && password !== 'password123') {
      return res.status(401).json({ success: false, error: 'Incorrect password. Please try again.' });
    }

    // If client, resolve client object
    let clientObj = null;
    if (matchedUser.role === 'CLIENT') {
      clientObj = clients.find(
        (c) => c.email.toLowerCase() === matchedUser?.email.toLowerCase() || c.mobile === matchedUser?.mobile || c.id === matchedUser?.id.replace('user-', '')
      ) || clients[0];
    }

    recordAudit(matchedUser.id, matchedUser.name, matchedUser.role as any, 'USER_LOGIN', 'User', matchedUser.id, { email: matchedUser.email, role: matchedUser.role }, req.ip);

    return res.json({
      success: true,
      user: matchedUser,
      client: clientObj,
      tenant,
      token: `taxvault-token-${matchedUser.id}-${Date.now()}`,
      message: `Welcome back, ${matchedUser.name}!`,
    });
  } catch (err: any) {
    console.error('Login error:', err);
    return res.status(500).json({ success: false, error: err?.message || 'Server error during login' });
  }
});

// CLIENT SIGNUP
app.post('/api/auth/signup/client', (req: Request, res: Response) => {
  const { firstName, lastName, email, mobile, pan, dateOfBirth, address, password } = req.body;

  if (!firstName || !email || !mobile || !pan) {
    return res.status(400).json({ success: false, error: 'First Name, Email, Mobile Number, and PAN are required.' });
  }

  const cleanPan = pan.trim().toUpperCase();
  const panRegex = /^[A-Z]{5}[0-9]{4}[A-Z]{1}$/;
  if (!panRegex.test(cleanPan)) {
    return res.status(400).json({ success: false, error: 'Invalid PAN format. Standard format is 5 letters, 4 digits, 1 letter (e.g. ABCDE1234F).' });
  }

  // Check if client with PAN or email exists
  const existingClient = clients.find((c) => c.pan === cleanPan || c.email.toLowerCase() === email.trim().toLowerCase());
  if (existingClient) {
    let existingUser = users.find((u) => u.email.toLowerCase() === existingClient.email.toLowerCase());
    if (!existingUser) {
      existingUser = {
        id: `user-${existingClient.id}`,
        tenantId: tenant.id,
        mobile: existingClient.mobile,
        email: existingClient.email,
        name: `${existingClient.firstName} ${existingClient.lastName}`.trim(),
        role: 'CLIENT',
      };
      users.push(existingUser);
    }
    if (password) {
      userPasswords.set(existingUser.email.toLowerCase(), password);
    }
    return res.json({
      success: true,
      user: existingUser,
      client: existingClient,
      tenant,
      token: `taxvault-token-${existingUser.id}-${Date.now()}`,
      message: 'Welcome! Found your existing taxpayer profile.',
    });
  }

  // Create new Client
  const newClient: Client = {
    id: `client-${Date.now()}`,
    tenantId: tenant.id,
    firstName: firstName.trim(),
    lastName: (lastName || '').trim(),
    mobile: mobile.trim(),
    email: email.trim().toLowerCase(),
    pan: cleanPan,
    dateOfBirth: dateOfBirth || '1995-01-01',
    address: address || 'India',
    clientId: `TV-2026-${String(clients.length + 1).padStart(3, '0')}`,
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  };
  clients.unshift(newClient);

  // Create User
  const newUser: User = {
    id: `user-${newClient.id}`,
    tenantId: tenant.id,
    mobile: newClient.mobile,
    email: newClient.email,
    name: `${newClient.firstName} ${newClient.lastName}`.trim(),
    role: 'CLIENT',
  };
  users.push(newUser);

  if (password) {
    userPasswords.set(newUser.email.toLowerCase(), password);
  }

  // Auto-initialize new AY 2026–27 filing with requirements
  const newFiling: Filing = {
    id: `filing-${Date.now()}`,
    tenantId: tenant.id,
    clientId: newClient.id,
    clientName: `${newClient.firstName} ${newClient.lastName}`.trim(),
    panMasked: `${newClient.pan.slice(0, 2)}XXX${newClient.pan.slice(-4)}`,
    financialYear: 'FY 2025–26',
    assessmentYear: 'AY 2026–27',
    status: 'DOCUMENTS_REQUESTED',
    progress: 0,
    totalDocuments: 4,
    receivedDocuments: 0,
    feeAmount: 2500,
    paymentStatus: 'PENDING',
    panDobVerified: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  ['cat-1', 'cat-2', 'cat-4', 'cat-6'].forEach((catId, idx) => {
    const cat = categories.find((c) => c.id === catId);
    if (cat) {
      requirements.push({
        id: `req-${Date.now()}-${idx}`,
        filingId: newFiling.id,
        documentCategoryId: cat.id,
        categoryName: cat.name,
        name: cat.name + ' Copy',
        description: cat.description,
        required: true,
        status: 'PENDING',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      });
    }
  });

  filings.unshift(newFiling);

  recordAudit(newUser.id, newUser.name, 'CLIENT', 'CLIENT_SIGNUP', 'Client', newClient.id, { email: newUser.email, pan: cleanPan }, req.ip);

  res.status(201).json({
    success: true,
    user: newUser,
    client: newClient,
    filing: newFiling,
    tenant,
    token: `taxvault-token-${newUser.id}-${Date.now()}`,
    message: 'Taxpayer account created successfully!',
  });
});

// ADMIN SIGNUP
app.post('/api/auth/signup/admin', (req: Request, res: Response) => {
  const { name, firmName, email, mobile, icaiNumber, password } = req.body;

  if (!name || !email || !mobile) {
    return res.status(400).json({ success: false, error: 'Full Name, Email, and Mobile are required.' });
  }

  if (firmName) {
    tenant.brandName = firmName.trim();
  }

  const newAdminUser: User = {
    id: `user-ca-${Date.now()}`,
    tenantId: tenant.id,
    mobile: mobile.trim(),
    email: email.trim().toLowerCase(),
    name: name.startsWith('CA ') ? name.trim() : `CA ${name.trim()}`,
    role: 'CA_ADMIN',
  };

  users.unshift(newAdminUser);

  if (password) {
    userPasswords.set(newAdminUser.email.toLowerCase(), password);
  }

  const staffEntry: StaffMember = {
    id: `staff-${Date.now()}`,
    tenantId: tenant.id,
    userId: newAdminUser.id,
    name: newAdminUser.name,
    email: newAdminUser.email,
    mobile: newAdminUser.mobile,
    role: 'CA_ADMIN',
    permissions: ['all'],
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  };
  staffMembers.unshift(staffEntry);

  recordAudit(newAdminUser.id, newAdminUser.name, 'CA_ADMIN', 'CA_ADMIN_SIGNUP', 'User', newAdminUser.id, { email: newAdminUser.email, firmName, icaiNumber }, req.ip);

  res.status(201).json({
    success: true,
    user: newAdminUser,
    tenant,
    token: `taxvault-token-${newAdminUser.id}-${Date.now()}`,
    message: 'CA Firm Practice account registered successfully!',
  });
});

app.post('/api/auth/forgot-password', (req: Request, res: Response) => {
  const { emailOrMobile } = req.body;
  if (!emailOrMobile) {
    return res.status(400).json({ success: false, error: 'Email or mobile is required.' });
  }
  res.json({
    success: true,
    message: `A password reset link & OTP have been dispatched to ${emailOrMobile}. (Demo code: 123456)`,
  });
});

app.post('/api/auth/logout', (req: Request, res: Response) => {
  res.json({ success: true, message: 'Logged out successfully.' });
});

app.get('/api/v1/health', (req: Request, res: Response) => {
  res.json({ status: 'ok', service: 'TaxVault API', version: '1.0.0', tenant: tenant.brandName });
});

// AUTH - OTP
app.post('/api/v1/auth/send-otp', (req: Request, res: Response) => {
  const { mobile } = req.body;
  if (!mobile) {
    return res.status(400).json({ success: false, error: { code: 'INVALID_INPUT', message: 'Mobile number is required' } });
  }
  // Simulate OTP send
  res.json({ success: true, message: 'OTP sent successfully to ' + mobile, demoOtp: '123456' });
});

app.post('/api/v1/auth/verify-otp', (req: Request, res: Response) => {
  const { mobile, otp } = req.body;
  if (otp !== '123456' && otp !== '000000') {
    return res.status(401).json({ success: false, error: { code: 'INVALID_OTP', message: 'Invalid OTP code entered.' } });
  }
  // Lookup or create user
  let user = users.find((u) => u.mobile === mobile);
  if (!user) {
    user = {
      id: `user-${Date.now()}`,
      tenantId: tenant.id,
      mobile,
      email: `${mobile.replace(/\D/g, '')}@taxvault.client`,
      name: 'Client ' + mobile.slice(-4),
      role: 'CLIENT',
    };
    users.push(user);
  }
  recordAudit(user.id, user.name, user.role as any, 'USER_LOGIN', 'User', user.id, { mobile }, req.ip);
  res.json({ success: true, user, token: `jwt-simulated-${user.id}-${Date.now()}` });
});

// ME
app.get('/api/v1/me', (req: Request, res: Response) => {
  const userId = (req.headers['x-user-id'] as string) || 'user-client-1';
  const user = users.find((u) => u.id === userId) || users[2];
  res.json({ success: true, user, tenant, featureFlags });
});

// CLIENTS
app.get('/api/v1/clients', (req: Request, res: Response) => {
  const { search } = req.query;
  let result = [...clients];
  if (search) {
    const q = (search as string).toLowerCase();
    result = result.filter((c) => c.firstName.toLowerCase().includes(q) || c.lastName.toLowerCase().includes(q) || c.pan.toLowerCase().includes(q) || c.mobile.includes(q) || c.clientId.toLowerCase().includes(q));
  }
  res.json({ success: true, data: result });
});

app.post('/api/v1/clients', (req: Request, res: Response) => {
  const { firstName, lastName, mobile, email, pan, dateOfBirth, address } = req.body;
  if (!firstName || !mobile || !pan) {
    return res.status(400).json({ success: false, error: { code: 'MISSING_FIELDS', message: 'First name, mobile, and PAN are required.' } });
  }
  const newClient: Client = {
    id: `client-${Date.now()}`,
    tenantId: tenant.id,
    firstName,
    lastName: lastName || '',
    mobile,
    email: email || '',
    pan: pan.toUpperCase(),
    dateOfBirth: dateOfBirth || '1995-01-01',
    address: address || '',
    clientId: `TV-2025-${String(clients.length + 1).padStart(3, '0')}`,
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  };
  clients.unshift(newClient);

  // Auto-create user record for client
  users.push({
    id: `user-${newClient.id}`,
    tenantId: tenant.id,
    mobile: newClient.mobile,
    email: newClient.email,
    name: `${newClient.firstName} ${newClient.lastName}`.trim(),
    role: 'CLIENT',
  });

  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'CLIENT_CREATED', 'Client', newClient.id, { clientName: `${firstName} ${lastName}`, pan }, req.ip);
  res.status(201).json({ success: true, data: newClient });
});

app.get('/api/v1/clients/:id', (req: Request, res: Response) => {
  const client = clients.find((c) => c.id === req.params.id);
  if (!client) {
    return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Client not found' } });
  }
  const clientFilings = filings.filter((f) => f.clientId === client.id);
  res.json({ success: true, data: client, filings: clientFilings });
});

// FILINGS
app.get('/api/v1/filings', (req: Request, res: Response) => {
  const clientId = req.query.clientId as string;
  let list = [...filings];
  if (clientId) {
    list = list.filter((f) => f.clientId === clientId);
  }
  res.json({ success: true, data: list });
});

app.post('/api/v1/filings', (req: Request, res: Response) => {
  const { clientId, financialYear, assessmentYear, feeAmount, defaultRequirementCategoryIds } = req.body;
  const client = clients.find((c) => c.id === clientId);
  if (!client) {
    return res.status(404).json({ success: false, error: { code: 'CLIENT_NOT_FOUND', message: 'Client not found' } });
  }

  const newFiling: Filing = {
    id: `filing-${Date.now()}`,
    tenantId: tenant.id,
    clientId: client.id,
    clientName: `${client.firstName} ${client.lastName}`.trim(),
    panMasked: `${client.pan.slice(0, 2)}XXX${client.pan.slice(-4)}`,
    financialYear: financialYear || 'FY 2025–26',
    assessmentYear: assessmentYear || 'AY 2026–27',
    status: 'DOCUMENTS_REQUESTED',
    progress: 0,
    totalDocuments: 0,
    receivedDocuments: 0,
    feeAmount: feeAmount || 2500,
    paymentStatus: 'PENDING',
    panDobVerified: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  // Add selected default requirements
  const selectedCatIds: string[] = defaultRequirementCategoryIds || ['cat-1', 'cat-2', 'cat-4', 'cat-5', 'cat-6'];
  let reqCount = 0;
  selectedCatIds.forEach((catId) => {
    const cat = categories.find((c) => c.id === catId);
    if (cat) {
      reqCount++;
      requirements.push({
        id: `req-${Date.now()}-${reqCount}`,
        filingId: newFiling.id,
        documentCategoryId: cat.id,
        categoryName: cat.name,
        name: cat.name + ' Upload',
        description: cat.description,
        required: true,
        status: 'PENDING',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      });
    }
  });

  newFiling.totalDocuments = reqCount;
  filings.unshift(newFiling);

  // Send Notification
  notifications.unshift({
    id: `notif-${Date.now()}`,
    tenantId: tenant.id,
    clientId: client.id,
    filingId: newFiling.id,
    type: 'DOCUMENT_REQUESTED',
    title: `New Tax Filing Created (${newFiling.financialYear})`,
    message: `Your CA has initiated your tax filing. Please upload required documents.`,
    read: false,
    createdAt: new Date().toISOString(),
  });

  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'FILING_CREATED', 'Filing', newFiling.id, { clientName: newFiling.clientName, FY: newFiling.financialYear }, req.ip);
  res.status(201).json({ success: true, data: newFiling });
});

app.get('/api/v1/filings/:id', (req: Request, res: Response) => {
  const filing = filings.find((f) => f.id === req.params.id);
  if (!filing) {
    return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Filing not found' } });
  }
  const filingReqs = requirements.filter((r) => r.filingId === filing.id);
  const client = clients.find((c) => c.id === filing.clientId);
  res.json({ success: true, data: filing, requirements: filingReqs, client });
});

app.patch('/api/v1/filings/:id/status', (req: Request, res: Response) => {
  const { status } = req.body as { status: FilingStatus };
  const filing = filings.find((f) => f.id === req.params.id);
  if (!filing) {
    return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Filing not found' } });
  }

  const oldStatus = filing.status;
  filing.status = status;
  filing.updatedAt = new Date().toISOString();

  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'FILING_STATUS_CHANGED', 'Filing', filing.id, { oldStatus, newStatus: status }, req.ip);

  // Send notification on key status transitions
  if (status === 'DOCUMENTS_READY') {
    notifications.unshift({
      id: `notif-${Date.now()}`,
      tenantId: tenant.id,
      clientId: filing.clientId,
      filingId: filing.id,
      type: 'DOCUMENTS_READY',
      title: 'Tax Documents Ready',
      message: 'Your ITR tax computation and filing acknowledgement are ready. Complete payment to access them.',
      read: false,
      createdAt: new Date().toISOString(),
    });
  }

  res.json({ success: true, data: filing });
});

// REQUIREMENTS & MISSING DOCUMENTS
app.get('/api/v1/filings/:id/requirements', (req: Request, res: Response) => {
  const reqs = requirements.filter((r) => r.filingId === req.params.id);
  res.json({ success: true, data: reqs });
});

app.post('/api/v1/filings/:id/requirements', (req: Request, res: Response) => {
  const { documentCategoryId, name, description, required } = req.body;
  const filing = filings.find((f) => f.id === req.params.id);
  if (!filing) {
    return res.status(404).json({ success: false, error: { code: 'FILING_NOT_FOUND', message: 'Filing not found' } });
  }
  const cat = categories.find((c) => c.id === documentCategoryId) || categories[0];
  const newReq: DocumentRequirement = {
    id: `req-${Date.now()}`,
    filingId: filing.id,
    documentCategoryId: cat.id,
    categoryName: cat.name,
    name: name || cat.name,
    description: description || cat.description,
    required: required !== undefined ? required : true,
    status: 'PENDING',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  requirements.push(newReq);
  filing.totalDocuments += 1;
  filing.status = 'ADDITIONAL_DOCUMENTS_REQUIRED';

  notifications.unshift({
    id: `notif-${Date.now()}`,
    tenantId: tenant.id,
    clientId: filing.clientId,
    filingId: filing.id,
    type: 'ADDITIONAL_DOCUMENT_REQUIRED',
    title: `Document Requested: ${newReq.name}`,
    message: `Your CA has requested: ${newReq.name}. Please upload it at your earliest convenience.`,
    read: false,
    createdAt: new Date().toISOString(),
  });

  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'DOCUMENT_REQUESTED', 'DocumentRequirement', newReq.id, { filingId: filing.id, requirementName: newReq.name }, req.ip);
  res.status(201).json({ success: true, data: newReq });
});

// SIGNED UPLOAD URL (SIMULATED STORAGE KEY GENERATION)
app.post('/api/v1/documents/upload-url', (req: Request, res: Response) => {
  const { filingId, requirementId, fileName, fileType, fileSize } = req.body;
  if (!filingId || !requirementId || !fileName) {
    return res.status(400).json({ success: false, error: { code: 'INVALID_INPUT', message: 'filingId, requirementId, and fileName required' } });
  }

  // Validate File Size (Max 25MB)
  if (fileSize && fileSize > 25 * 1024 * 1024) {
    return res.status(400).json({ success: false, error: { code: 'FILE_TOO_LARGE', message: 'File size exceeds 25MB limit.' } });
  }

  const filing = filings.find((f) => f.id === filingId);
  const reqItem = requirements.find((r) => r.id === requirementId);

  if (!filing || !reqItem) {
    return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Filing or requirement not found' } });
  }

  const versionId = `ver-${Date.now()}`;
  const storageKey = `tenant/${tenant.id}/clients/${filing.clientId}/filings/${filing.id}/documents/${reqItem.id}/versions/${versionId}/${encodeURIComponent(fileName)}`;
  const uploadToken = crypto.createHmac('sha256', 'taxvault-secret').update(storageKey).digest('hex');

  res.json({
    success: true,
    uploadUrl: `/api/v1/documents/mock-upload-target?token=${uploadToken}`,
    storageKey,
    versionId,
    expiresInSeconds: 300,
  });
});

// CONFIRM UPLOAD (CREATES / UPDATES DOCUMENT VERSION & FILING STATUS)
app.post('/api/v1/documents/confirm-upload', (req: Request, res: Response) => {
  const { requirementId, fileName, fileType, fileSize, simulatedContentUrl } = req.body;
  const reqItem = requirements.find((r) => r.id === requirementId);
  if (!reqItem) {
    return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Requirement not found' } });
  }

  const filing = filings.find((f) => f.id === reqItem.filingId);
  if (!filing) {
    return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Filing not found' } });
  }

  const newVersionNumber = reqItem.currentDocument ? reqItem.currentDocument.versions.length + 1 : 1;
  const newVersion: DocumentVersion = {
    id: `ver-${Date.now()}`,
    documentId: reqItem.currentDocument ? reqItem.currentDocument.id : `doc-${Date.now()}`,
    versionNumber: newVersionNumber,
    fileName: fileName || 'Uploaded_Document.pdf',
    fileType: fileType || 'application/pdf',
    fileSize: fileSize || 500000,
    contentUrl: simulatedContentUrl || 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    uploadedAt: new Date().toISOString(),
    uploadedBy: filing.clientName,
  };

  if (!reqItem.currentDocument) {
    reqItem.currentDocument = {
      id: newVersion.documentId,
      status: 'UNDER_REVIEW',
      latestVersion: newVersion,
      versions: [newVersion],
    };
  } else {
    reqItem.currentDocument.versions.unshift(newVersion);
    reqItem.currentDocument.latestVersion = newVersion;
    reqItem.currentDocument.status = 'UNDER_REVIEW';
  }

  reqItem.status = 'UNDER_REVIEW';
  reqItem.rejectionReason = undefined;
  reqItem.updatedAt = new Date().toISOString();

  // Recalculate filing received documents & progress
  const filingReqs = requirements.filter((r) => r.filingId === filing.id);
  const received = filingReqs.filter((r) => r.status === 'APPROVED' || r.status === 'UNDER_REVIEW').length;
  filing.receivedDocuments = received;
  filing.progress = Math.round((received / Math.max(1, filing.totalDocuments)) * 80);

  if (filing.status === 'DOCUMENTS_REQUESTED' || filing.status === 'ADDITIONAL_DOCUMENTS_REQUIRED') {
    filing.status = 'DOCUMENTS_PARTIALLY_SUBMITTED';
  }
  if (received >= filing.totalDocuments) {
    filing.status = 'DOCUMENTS_SUBMITTED';
  }

  recordAudit('user-client-1', filing.clientName, 'CLIENT', 'DOCUMENT_UPLOADED', 'DocumentRequirement', reqItem.id, { requirementName: reqItem.name, versionNumber: newVersionNumber, fileName: newVersion.fileName }, req.ip);

  res.json({ success: true, requirement: reqItem, filing });
});

// APPROVE / REJECT DOCUMENT BY CA
app.patch('/api/v1/documents/:requirementId/approve', (req: Request, res: Response) => {
  const reqItem = requirements.find((r) => r.id === req.params.requirementId);
  if (!reqItem || !reqItem.currentDocument) {
    return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Requirement or uploaded document not found' } });
  }

  reqItem.status = 'APPROVED';
  reqItem.currentDocument.status = 'APPROVED';
  reqItem.rejectionReason = undefined;
  reqItem.updatedAt = new Date().toISOString();

  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'DOCUMENT_APPROVED', 'DocumentRequirement', reqItem.id, { requirementName: reqItem.name }, req.ip);
  res.json({ success: true, data: reqItem });
});

app.patch('/api/v1/documents/:requirementId/reject', (req: Request, res: Response) => {
  const { reason } = req.body;
  const reqItem = requirements.find((r) => r.id === req.params.requirementId);
  if (!reqItem || !reqItem.currentDocument) {
    return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Requirement or uploaded document not found' } });
  }

  reqItem.status = 'REJECTED';
  reqItem.currentDocument.status = 'REJECTED';
  reqItem.rejectionReason = reason || 'Document rejected by CA. Please re-upload a clear and complete version.';
  reqItem.updatedAt = new Date().toISOString();

  const filing = filings.find((f) => f.id === reqItem.filingId);
  if (filing) {
    filing.status = 'ADDITIONAL_DOCUMENTS_REQUIRED';
    notifications.unshift({
      id: `notif-${Date.now()}`,
      tenantId: tenant.id,
      clientId: filing.clientId,
      filingId: filing.id,
      type: 'DOCUMENT_REJECTED',
      title: `Document Replacement Requested: ${reqItem.name}`,
      message: reqItem.rejectionReason,
      read: false,
      createdAt: new Date().toISOString(),
    });
  }

  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'DOCUMENT_REJECTED', 'DocumentRequirement', reqItem.id, { requirementName: reqItem.name, reason: reqItem.rejectionReason }, req.ip);
  res.json({ success: true, data: reqItem });
});

// CA UPLOADS COMPLETED TAX DOCUMENTS (ITR Ack & Computation)
app.post('/api/v1/filings/:id/upload-final', (req: Request, res: Response) => {
  const filing = filings.find((f) => f.id === req.params.id);
  if (!filing) {
    return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Filing not found' } });
  }

  const { title, fileName, simulatedContentUrl } = req.body;

  const newReq: DocumentRequirement = {
    id: `req-final-${Date.now()}`,
    filingId: filing.id,
    documentCategoryId: 'cat-10',
    categoryName: 'ITR Acknowledgement & Tax Computation',
    name: title || 'ITR Acknowledgement & Computation',
    description: 'Final verified tax documents generated by CA',
    required: true,
    status: 'APPROVED',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    currentDocument: {
      id: `doc-final-${Date.now()}`,
      status: 'APPROVED',
      latestVersion: {
        id: `ver-final-${Date.now()}`,
        documentId: `doc-final-${Date.now()}`,
        versionNumber: 1,
        fileName: fileName || 'ITR_V_Acknowledgement_Verified.pdf',
        fileType: 'application/pdf',
        fileSize: 750000,
        contentUrl: simulatedContentUrl || 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        uploadedAt: new Date().toISOString(),
        uploadedBy: 'CA Rajesh Kothari',
      },
      versions: [],
    },
  };

  requirements.push(newReq);
  filing.status = 'PAYMENT_PENDING';
  filing.progress = 95;

  notifications.unshift({
    id: `notif-${Date.now()}`,
    tenantId: tenant.id,
    clientId: filing.clientId,
    filingId: filing.id,
    type: 'DOCUMENTS_READY',
    title: 'Your Filing is Complete!',
    message: `Your CA has uploaded your completed ITR V and Tax Computation sheet. Pay ₹${filing.feeAmount} to unlock downloads.`,
    read: false,
    createdAt: new Date().toISOString(),
  });

  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'FINAL_DOCUMENTS_UPLOADED', 'Filing', filing.id, { fileName }, req.ip);
  res.json({ success: true, filing, requirement: newReq });
});

// PAYMENTS (RAZORPAY ORDER CREATION & WEBHOOK HANDLER)
app.post('/api/v1/filings/:id/payment/order', (req: Request, res: Response) => {
  const filing = filings.find((f) => f.id === req.params.id);
  if (!filing) {
    return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Filing not found' } });
  }

  const razorpayOrderId = `order_RZP${Math.floor(100000 + Math.random() * 900000)}`;
  const payment: Payment = {
    id: `pay-${Date.now()}`,
    tenantId: tenant.id,
    clientId: filing.clientId,
    filingId: filing.id,
    razorpayOrderId,
    amount: filing.feeAmount,
    currency: 'INR',
    status: 'CREATED',
    createdAt: new Date().toISOString(),
  };

  payments.unshift(payment);
  recordAudit('user-client-1', filing.clientName, 'CLIENT', 'PAYMENT_CREATED', 'Payment', payment.id, { amount: payment.amount, razorpayOrderId }, req.ip);

  res.json({
    success: true,
    payment,
    razorpayKey: 'rzp_test_TaxVaultKey123',
    amountInPaise: filing.feeAmount * 100,
    currency: 'INR',
  });
});

// WEBHOOK / VERIFY PAYMENT SIGNATURE
app.post('/api/v1/payments/webhook', (req: Request, res: Response) => {
  const { razorpayOrderId, razorpayPaymentId, razorpaySignature } = req.body;
  const payment = payments.find((p) => p.razorpayOrderId === razorpayOrderId) || payments[0];

  if (!payment) {
    return res.status(404).json({ success: false, error: { code: 'PAYMENT_NOT_FOUND', message: 'Order not found' } });
  }

  // Simulated server-side HMAC validation check
  payment.status = 'SUCCESS';
  payment.razorpayPaymentId = razorpayPaymentId || `pay_RZP${Math.floor(100000 + Math.random() * 900000)}`;
  payment.paymentMethod = 'UPI / NetBanking';
  payment.paidAt = new Date().toISOString();

  const filing = filings.find((f) => f.id === payment.filingId);
  if (filing) {
    filing.paymentStatus = 'SUCCESS';
    filing.status = 'PAYMENT_COMPLETED';
    filing.progress = 98;

    notifications.unshift({
      id: `notif-${Date.now()}`,
      tenantId: tenant.id,
      clientId: filing.clientId,
      filingId: filing.id,
      type: 'PAYMENT_SUCCESSFUL',
      title: 'Payment Confirmed',
      message: `Payment of ₹${payment.amount} received. Please enter your PAN & Date of Birth to verify identity and unlock downloads.`,
      read: false,
      createdAt: new Date().toISOString(),
    });
  }

  recordAudit('SYSTEM', 'Razorpay Webhook', 'SYSTEM', 'PAYMENT_SUCCESS', 'Payment', payment.id, { amount: payment.amount, razorpayPaymentId: payment.razorpayPaymentId }, req.ip);
  res.json({ success: true, message: 'Payment verified and marked SUCCESS', payment });
});

// PAN + DOB IDENTITY VERIFICATION FOR DOCUMENT ACCESS (WITH RATE LIMITING)
app.post('/api/v1/filings/:id/verify-identity', (req: Request, res: Response) => {
  const { pan, dateOfBirth } = req.body;
  const filing = filings.find((f) => f.id === req.params.id);
  if (!filing) {
    return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Filing not found' } });
  }

  const client = clients.find((c) => c.id === filing.clientId);
  if (!client) {
    return res.status(404).json({ success: false, error: { code: 'CLIENT_NOT_FOUND', message: 'Client not found' } });
  }

  // Rate Limiting Check: Max 5 attempts per 15 minutes
  const now = Date.now();
  const attemptInfo = panVerificationAttemptsMap.get(client.id) || { attempts: 0 };

  if (attemptInfo.lockedUntil && now < attemptInfo.lockedUntil) {
    const remainingMins = Math.ceil((attemptInfo.lockedUntil - now) / 60000);
    recordAudit('user-client-1', client.firstName + ' ' + client.lastName, 'CLIENT', 'PAN_VERIFICATION_LOCKED', 'Client', client.id, { remainingMins }, req.ip);
    return res.status(429).json({
      success: false,
      error: { code: 'TOO_MANY_ATTEMPTS', message: `Too many failed identity attempts. Please wait ${remainingMins} minutes before trying again.` },
    });
  }

  const cleanPan = (pan || '').trim().toUpperCase();
  const cleanDob = (dateOfBirth || '').trim();

  const isPanMatch = cleanPan === client.pan;
  const isDobMatch = cleanDob === client.dateOfBirth;

  if (!isPanMatch || !isDobMatch) {
    attemptInfo.attempts += 1;
    if (attemptInfo.attempts >= 5) {
      attemptInfo.lockedUntil = now + 15 * 60 * 1000; // 15 mins lock
    }
    panVerificationAttemptsMap.set(client.id, attemptInfo);

    recordAudit('user-client-1', client.firstName + ' ' + client.lastName, 'CLIENT', 'PAN_VERIFICATION_FAILED', 'Client', client.id, { attemptCount: attemptInfo.attempts }, req.ip);

    return res.status(401).json({
      success: false,
      error: { code: 'VERIFICATION_FAILED', message: 'Invalid PAN or Date of Birth entered. Please verify credentials on file.' },
    });
  }

  // Success: Clear attempts & mark verified
  panVerificationAttemptsMap.delete(client.id);
  filing.panDobVerified = true;
  if (filing.paymentStatus === 'SUCCESS') {
    filing.status = 'DOWNLOAD_UNLOCKED';
    filing.progress = 100;
  }

  recordAudit('user-client-1', client.firstName + ' ' + client.lastName, 'CLIENT', 'PAN_VERIFICATION_SUCCESS', 'Client', client.id, {}, req.ip);

  res.json({
    success: true,
    message: 'Identity verified successfully!',
    filing,
  });
});

// SERVER-SIDE DOWNLOAD LOCK & SHORT-LIVED SIGNED DOWNLOAD URL
app.post('/api/v1/documents/:requirementId/download-url', (req: Request, res: Response) => {
  const reqItem = requirements.find((r) => r.id === req.params.requirementId);
  if (!reqItem || !reqItem.currentDocument) {
    return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Document requirement not found' } });
  }

  const filing = filings.find((f) => f.id === reqItem.filingId);
  if (!filing) {
    return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Filing not found' } });
  }

  // SERVER-SIDE LOCK CHECKS
  // Check 1: Payment Check
  if (filing.paymentStatus !== 'SUCCESS') {
    return res.status(403).json({
      success: false,
      error: {
        code: 'PAYMENT_REQUIRED',
        message: 'Payment is pending. Please complete fee payment to unlock document download.',
      },
    });
  }

  // Check 2: Identity Verification Check (PAN + DOB)
  if (!filing.panDobVerified) {
    return res.status(403).json({
      success: false,
      error: {
        code: 'IDENTITY_VERIFICATION_REQUIRED',
        message: 'PAN and Date of Birth verification required before downloading financial tax documents.',
      },
    });
  }

  // Generate 5-Minute Short-Lived Signed URL
  const version = reqItem.currentDocument.latestVersion;
  const expiresAt = new Date(Date.now() + 5 * 60 * 1000).toISOString(); // 5 minutes
  const signedToken = crypto.createHmac('sha256', 'taxvault-dl-secret').update(`${version.id}-${expiresAt}`).digest('hex');

  const downloadUrl = version.contentUrl || 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf';

  // Log Download Event
  const dlEvent: DownloadEvent = {
    id: `dl-${Date.now()}`,
    tenantId: tenant.id,
    clientId: filing.clientId,
    filingId: filing.id,
    documentId: reqItem.currentDocument.id,
    documentName: reqItem.name,
    userId: 'user-client-1',
    userName: filing.clientName,
    timestamp: new Date().toISOString(),
    ipAddress: req.ip || '127.0.0.1',
    userAgent: (req.headers['user-agent'] as string) || 'TaxVault Client Web',
    success: true,
  };
  downloadEvents.unshift(dlEvent);

  recordAudit('user-client-1', filing.clientName, 'CLIENT', 'DOCUMENT_DOWNLOADED', 'DocumentRequirement', reqItem.id, { documentName: reqItem.name, fileName: version.fileName }, req.ip);

  res.json({
    success: true,
    downloadUrl,
    signedToken,
    expiresAt,
    expiresInSeconds: 300,
    fileName: version.fileName,
  });
});

// NOTIFICATIONS
app.get('/api/v1/notifications', (req: Request, res: Response) => {
  const clientId = req.query.clientId as string;
  let list = [...notifications];
  if (clientId) {
    list = list.filter((n) => n.clientId === clientId);
  }
  res.json({ success: true, data: list });
});

app.post('/api/v1/notifications/:id/read', (req: Request, res: Response) => {
  const notif = notifications.find((n) => n.id === req.params.id);
  if (notif) {
    notif.read = true;
  }
  res.json({ success: true, data: notif });
});

// AUDIT LOGS & DOWNLOAD HISTORY
app.get('/api/v1/audit-logs', (req: Request, res: Response) => {
  res.json({ success: true, data: auditLogs });
});

app.get('/api/v1/download-events', (req: Request, res: Response) => {
  res.json({ success: true, data: downloadEvents });
});

// STAFF & PERMISSIONS
app.get('/api/v1/staff', (req: Request, res: Response) => {
  res.json({ success: true, data: staffMembers });
});

app.post('/api/v1/staff', (req: Request, res: Response) => {
  const { name, email, mobile, permissions } = req.body;
  if (!name || !email) {
    return res.status(400).json({ success: false, error: { code: 'INVALID_INPUT', message: 'Name and email required' } });
  }

  const staff: StaffMember = {
    id: `staff-${Date.now()}`,
    tenantId: tenant.id,
    userId: `user-staff-${Date.now()}`,
    name,
    email,
    mobile: mobile || '+91 90000 00000',
    role: 'CA_STAFF',
    permissions: permissions || ['clients:read', 'filings:read', 'documents:read', 'documents:approve', 'documents:reject'],
    status: 'INVITED',
    createdAt: new Date().toISOString(),
  };

  staffMembers.unshift(staff);
  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'STAFF_INVITED', 'StaffMember', staff.id, { email, role: staff.role }, req.ip);
  res.status(201).json({ success: true, data: staff });
});

// BULK OPERATIONS
app.post('/api/v1/bulk/create-filings', (req: Request, res: Response) => {
  const { clientIds, financialYear, assessmentYear, feeAmount } = req.body;
  if (!clientIds || !Array.isArray(clientIds) || clientIds.length === 0) {
    return res.status(400).json({ success: false, error: { code: 'INVALID_INPUT', message: 'Array of clientIds required' } });
  }

  let createdCount = 0;
  clientIds.forEach((cId) => {
    const client = clients.find((c) => c.id === cId);
    if (client) {
      createdCount++;
      const newFiling: Filing = {
        id: `filing-bulk-${Date.now()}-${createdCount}`,
        tenantId: tenant.id,
        clientId: client.id,
        clientName: `${client.firstName} ${client.lastName}`.trim(),
        panMasked: `${client.pan.slice(0, 2)}XXX${client.pan.slice(-4)}`,
        financialYear: financialYear || 'FY 2025–26',
        assessmentYear: assessmentYear || 'AY 2026–27',
        status: 'DOCUMENTS_REQUESTED',
        progress: 0,
        totalDocuments: 4,
        receivedDocuments: 0,
        feeAmount: feeAmount || 2500,
        paymentStatus: 'PENDING',
        panDobVerified: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
      filings.unshift(newFiling);

      // Add standard default requirements
      ['cat-1', 'cat-2', 'cat-4', 'cat-6'].forEach((catId, idx) => {
        const cat = categories.find((c) => c.id === catId);
        if (cat) {
          requirements.push({
            id: `req-bulk-${Date.now()}-${createdCount}-${idx}`,
            filingId: newFiling.id,
            documentCategoryId: cat.id,
            categoryName: cat.name,
            name: cat.name + ' Upload',
            description: cat.description,
            required: true,
            status: 'PENDING',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          });
        }
      });
    }
  });

  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'BULK_FILINGS_CREATED', 'Filing', 'bulk', { count: createdCount, FY: financialYear }, req.ip);
  res.json({ success: true, message: `Successfully initiated ${createdCount} filings in bulk.`, count: createdCount });
});

app.post('/api/v1/bulk/remind-missing', (req: Request, res: Response) => {
  const missingFilings = filings.filter((f) => f.status === 'DOCUMENTS_REQUESTED' || f.status === 'ADDITIONAL_DOCUMENTS_REQUIRED' || f.status === 'DOCUMENTS_PARTIALLY_SUBMITTED');
  missingFilings.forEach((f) => {
    notifications.unshift({
      id: `notif-bulk-${Date.now()}-${Math.random()}`,
      tenantId: tenant.id,
      clientId: f.clientId,
      filingId: f.id,
      type: 'DOCUMENT_REQUESTED',
      title: 'Reminder: Pending Tax Documents',
      message: 'Your CA is awaiting your document upload to proceed with your FY 2025–26 tax filing.',
      read: false,
      createdAt: new Date().toISOString(),
    });
  });

  recordAudit('user-ca-admin', 'CA Rajesh Kothari', 'CA_ADMIN', 'BULK_REMINDERS_SENT', 'Notification', 'bulk', { count: missingFilings.length }, req.ip);
  res.json({ success: true, message: `Sent document upload reminders to ${missingFilings.length} clients.` });
});

// V2 AI OCR PREVIEW (SIMULATION WITH CONFIDENCE SCORES)
app.post('/api/v1/v2/ocr-preview', (req: Request, res: Response) => {
  const { fileName } = req.body;
  const simulatedExtractedData = {
    documentType: 'FORM_16',
    classificationConfidence: 0.984,
    extractedFields: {
      employeeName: { value: 'Yuvaraj Vasam', confidence: 0.992, source: 'Page 1, Header' },
      pan: { value: 'ABCDE1234F', confidence: 0.998, source: 'Page 1, Part A' },
      employerName: { value: 'Tata Consultancy Services Ltd', confidence: 0.981, source: 'Page 1, Employer Details' },
      assessmentYear: { value: '2026-27', confidence: 0.999, source: 'Page 1' },
      grossSalary: { value: 1450000, confidence: 0.976, source: 'Page 2, Line 1a' },
      tdsDeducted: { value: 162500, confidence: 0.989, source: 'Page 2, Line 17' },
    },
    validationStatus: 'PASSED',
    mismatches: [],
  };

  res.json({ success: true, data: simulatedExtractedData });
});

// V2 GOVERNMENT ERI ADAPTER INTERFACE
app.get('/api/v1/v2/eri-status', (req: Request, res: Response) => {
  res.json({
    success: true,
    featureEnabled: featureFlags.ITD_ERI,
    adapterName: 'IncomeTaxERIAdapter',
    itdApiEnabled: false,
    message: 'Income Tax Department (ITD) ERI/API integration is guarded behind adapter interface and feature flags. Requires confirmed Type-2 ERI authorization and ITD API production credentials.',
    documentedEndpoints: [
      'POST /auth/login',
      'POST /client/add',
      'GET /client/prefill',
      'POST /return/validate',
      'POST /return/submit',
      'POST /return/e-verify',
      'GET /return/acknowledgement',
    ],
  });
});

// VITE MIDDLEWARE / STATIC SERVING
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req: Request, res: Response) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`[TaxVault Server] Running on http://localhost:${PORT}`);
  });
}

startServer();
